# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-08 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('telesurvideos', '0002_auto_20170107_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolistpluginmodel',
            name='mostrar_banner',
            field=models.BooleanField(default=False, help_text='Mostrar encabezado con banner de programa', verbose_name='mostrar banner'),
        ),
        migrations.AlterField(
            model_name='videolistpluginmodel',
            name='categorias',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('politica', 'Politics'), ('economia', 'Economy'), ('medio-ambiente', 'Environment'), ('cultura', 'Culture'), ('deportes', 'Sports'), ('ciencia', 'Science'), ('salud', 'Health'), ('ciencia-y-tecnologia', 'Science & Technology')], max_length=84, null=True, verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='videolistpluginmodel',
            name='corresponsales',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('dimitri-odonell', "Dimitri O'Donnell"), ('iain-bruce', 'Iain Bruce'), ('jorge-gestoso', 'Jorge Gestoso'), ('rachael-boothroyd', 'Rachael Boothroyd'), ('clayton-conn', 'Clayton Conn'), ('sydney-kashiwagi', 'Sydney Kashiwagi'), ('leo-poblete', 'Leo Poblete'), ('gerardo-torres', 'Gerardo Torres'), ('noor-harazeen', 'Noor Harazeen'), ('liz-scherffius', 'Liz Scherffius'), ('rael-mora', 'Rael Mora'), ('jorge-gestoso', 'Jorge Gestoso'), ('stephanie-montalan', 'Stephanie Montalan'), ('stephanie-kennedy', 'Stephanie Kennedy'), ('alexandra-hall', 'Alexandra Hall'), ('alison-kentish', 'Alison Kentish'), ('natalia-margarita', 'Natalia Margarita'), ('laureano-ponce', 'Laureano Ponce'), ('hazem-abdullah', 'Hazem Abdullah'), ('bianca-perez', 'Bianca Perez'), ('cody-weddle', 'Cody Weddle')], max_length=308, null=True, verbose_name='correspondants'),
        ),
        migrations.AlterField(
            model_name='videolistpluginmodel',
            name='layout',
            field=models.TextField(blank=True, help_text='1, q => full column | 2, w => half column | 3, e => third of column| 4, r => one fourth of column | 6, t => two thirds of column', verbose_name='layout'),
        ),
        migrations.AlterField(
            model_name='videolistpluginmodel',
            name='limite',
            field=models.PositiveIntegerField(default=20, verbose_name='Limit'),
        ),
        migrations.AlterField(
            model_name='videolistpluginmodel',
            name='mostrar_descripcion',
            field=models.BooleanField(default=True, verbose_name='show description'),
        ),
        migrations.AlterField(
            model_name='videolistpluginmodel',
            name='mostrar_fecha',
            field=models.CharField(blank=True, choices=[('rel', 'Relative date (X time ago)'), ('f', 'Full date'), ('fh', 'Full date and time'), ('con', 'Relative if date is today, full date otherwise'), (None, "Don't display date")], default='con', max_length=3, null=True, verbose_name='show date'),
        ),
        migrations.AlterField(
            model_name='videolistpluginmodel',
            name='mostrar_mas',
            field=models.TextField(blank=True, help_text='1, q => full column | 2, w => half column | 3, e => third of column| 4, r => one fourth of column | 6, t => two thirds of column', verbose_name='show more'),
        ),
        migrations.AlterField(
            model_name='videolistpluginmodel',
            name='mostrar_tags',
            field=models.BooleanField(default=True, verbose_name='show tags'),
        ),
        migrations.AlterField(
            model_name='videolistpluginmodel',
            name='mostrar_titulo',
            field=models.BooleanField(default=True, verbose_name='show title'),
        ),
        migrations.AlterField(
            model_name='videolistpluginmodel',
            name='paises',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('afganistan', 'Afghanistan'), ('alemania', 'Germany'), ('angola', 'Angola'), ('arabia-saudita', 'Saudi Arabia'), ('argelia', 'Algeria'), ('argentina', 'Argentina'), ('armenia', 'Armenia'), ('australia', 'Australia'), ('austria', 'Austria'), ('azerbaijan', 'Azerbaijan'), ('bahamas', 'Bahamas'), ('bangladesh', 'Bangladesh'), ('barein', 'Bahrain'), ('belgica', 'Belgium'), ('bermudas', 'Bermuda'), ('bielorrusia', 'Belarus'), ('bolivia', 'Bolivia, Plurinational State of'), ('bosnia', 'Bosnia and Herzegovina'), ('botswana', 'Botswana'), ('brasil', 'Brazil'), ('bulgaria', 'Bulgaria'), ('burkina-faso', 'Burkina Faso'), ('cabo-verde', 'Cape Verde'), ('camboya', 'Cambodia'), ('camerun', 'Cameroon'), ('canada', 'Canada'), ('chad', 'Chad'), ('chile', 'Chile'), ('china', 'China'), ('chipre', 'Cyprus'), ('colombia', 'Colombia'), ('comoras', 'Comoros'), ('corea-del-norte', "Korea, Democratic People's Republic of"), ('corea-del-sur', 'Korea, Republic of'), ('costa-de-marfil', "C\xf4te d'Ivoire"), ('costa-rica', 'Costa Rica'), ('croacia', 'Croatia'), ('cuba', 'Cuba'), ('curazao', 'Cura\xe7ao'), ('dinamarca', 'Denmark'), ('dominica', 'Dominica'), ('ecuador', 'Ecuador'), ('egipto', 'Egypt'), ('el-salvador', 'El Salvador'), ('emiratos-arabes', 'United Arab Emirates'), ('escocia', 'Seychelles'), ('eslovaquia', 'Eslovaquia'), ('eslovenia', 'Slovenia'), ('espana', 'Spain'), ('estados-unidos', 'United States'), ('estonia', 'Estonia'), ('etiopia', 'Ethiopia'), ('filipinas', 'Philippines'), ('finlandia', 'Finland'), ('francia', 'France'), ('gabon', 'Gabon'), ('gambia', 'Gambia'), ('georgia', 'Georgia'), ('ghana', 'Ghana'), ('granada', 'Grenada'), ('grecia', 'Greece'), ('guatemala', 'Guatemala'), ('guinea', 'Guinea'), ('guinea-bissau', 'Guinea-Bissau'), ('guyana', 'Guyana'), ('haiti', 'Haiti'), ('holanda', 'Netherlands'), ('honduras', 'Honduras'), ('hungria', 'Hungary'), ('india', 'India'), ('indonesia', 'Indonesia'), ('inglaterra', 'United Kingdom'), ('irak', 'Iraq'), ('iran', 'Iran, Islamic Republic of'), ('irlanda', 'Ireland'), ('irlanda-del-norte', 'Irlanda del Norte'), ('islandia', 'Iceland'), ('islas-fiji', 'Fiji'), ('israel', 'Israel'), ('italia', 'Italy'), ('jamaica', 'Jamaica'), ('japon', 'Japan'), ('jordania', 'Jordan'), ('kazajistan', 'Kazakhstan'), ('kenia', 'Kenya'), ('kirguistan', 'Kyrgyzstan'), ('kosovo', 'Kosovo'), ('kuwait', 'Kuwait'), ('laos', "Lao People's Democratic Republic"), ('lesoto', 'Lesotho'), ('libano', 'Lebanon'), ('liberia', 'Liberia'), ('libia', 'Libya'), ('lituania', 'Lithuania'), ('luxemburgo', 'Luxembourg'), ('madagascar', 'Madagascar'), ('malasia', 'Malaysia'), ('maldivas', 'Maldives'), ('mali', 'Mali'), ('malta', 'Malta'), ('marruecos', 'Morocco'), ('mauritania', 'Mauritania'), ('mexico', 'Mexico'), ('monaco', 'Monaco'), ('mongolia', 'Mongolia'), ('mozambique', 'Mozambique'), ('myanmar', 'Myanmar'), ('nepal', 'Nepal'), ('nicaragua', 'Nicaragua'), ('niger', 'Niger'), ('nigeria', 'Nigeria'), ('noruega', 'Norway'), ('nueva-zelanda', 'New Zealand'), ('oman', 'Oman'), ('osetia-del-sur', 'Osetia del Sur'), ('paises-bajos', 'New Zealand'), ('pakistan', 'Pakistan'), ('palestina', 'Palestine, State of'), ('panama', 'Panama'), ('papua-nueva-guinea', 'Nauru'), ('paraguay', 'Paraguay'), ('peru', 'Peru'), ('polonia', 'Poland'), ('portugal', 'Portugal'), ('puerto-rico', 'Puerto Rico'), ('qatar', 'Qatar'), ('reino-unido', 'Reino Unido'), ('republica-centroafricana', 'Central African Republic'), ('republica-checa', 'Rep\xfablica Checa'), ('republica-de-namibia', 'Namibia'), ('republica-democratica-del-congo', 'Congo, The Democratic Republic of the'), ('republica-democratica-del-congo', 'Congo, The Democratic Republic of the'), ('republica-dominicana', 'Dominican Republic'), ('ruanda', 'Rwanda'), ('rumania', 'Romania'), ('rusia', 'Russian Federation'), ('sahara-occidental', 'Western Sahara'), ('san-vicente-y-las-granadinas', 'Saint Vincent and the Grenadines'), ('santa-lucia', 'Saint Lucia'), ('senegal', 'Senegal'), ('serbia', 'Serbia'), ('sierra-leona', 'Sierra Leone'), ('singapur', 'Singapore'), ('siria', 'Syrian Arab Republic'), ('somalia', 'Somalia'), ('sri-lanka', 'Sri Lanka'), ('sudafrica', 'South Africa'), ('sudan', 'Sudan'), ('sudan-del-sur', 'South Sudan'), ('suecia', 'Sweden'), ('suiza', 'Switzerland'), ('surinam', 'Suriname'), ('tailandia', 'Thailand'), ('taiwan', 'Taiwan, Province of China'), ('tanzania', 'Tanzania, United Republic of'), ('tayikistan', 'Tajikistan'), ('timor-oriental', 'Timor-Leste'), ('tonga', 'Tonga'), ('trinidad-y-tobago', 'Trinidad and Tobago'), ('tunez', 'Tunisia'), ('turquia', 'Turkey'), ('ucrania', 'Ukraine'), ('uganda', 'Uganda'), ('uruguay', 'Uruguay'), ('vanuatu', 'Vanuatu'), ('vaticano', 'Holy See (Vatican City State)'), ('venezuela', 'Venezuela, Bolivarian Republic of'), ('vietnam', 'Viet Nam'), ('yemen', 'Yemen'), ('zambia', 'Zambia'), ('zimbabue', 'Zimbabwe')], max_length=1642, null=True, verbose_name='countries'),
        ),
        migrations.AlterField(
            model_name='videolistpluginmodel',
            name='programas',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('palestine-travel-show', 'Palestine Travel Show'), ('days-of-revolt', 'Days of Revolt'), ('the-empire-files', 'The Empire Files'), ('the-world-today', 'The World Today'), ('n-dont-stop', "\xd1 Don't Stop"), ('laura-flanders-show', 'Laura Flanders Show'), ('the-global-african', 'The Global African '), ('media-review', 'Media Review'), ('rear-window', 'Rear Window'), ('the-self-show', 'The Self Show'), ('interviews-from-caracas', 'Interviews from Caracas '), ('interviews-from-washington-dc', 'Interviews From Washington DC'), ('interviews-from-quito', 'Interviews from Quito'), ('interviews-from-havana', 'Interviews From Havana'), ('interviews-from-mexico', 'Interviews From Mexico'), ('imaginary-lines', 'Imaginary Lines'), ('cultura-latina', 'Cultura Latina'), ('telesur-weekly-roundup', 'teleSUR Weekly RoundUp'), ('inside-the-americas', 'Inside The Americas'), ('documentary', 'Documentary'), ('dossier', 'Dossier'), ('americans', 'Am\xe9ricans'), ('from-the-south', 'From The South'), ('just-cause', 'Just Cause'), ('atomun', 'Atomun'), ('open-files', 'Open Files'), ('telesur-reports', 'teleSUR Reports'), ('the-real-usa', 'The Real USA '), ('the-stories-behind-the-tweets', 'The Stories Behind the Tweets'), ('lives', 'Lives'), ('know-your-body', 'Know Your Body'), ('web-serial', 'Web Serial'), ('special-show', 'Special Show'), ('llama-time', 'Llama Time'), ('los-nuestros', 'Los Nuestros')], max_length=557, null=True, verbose_name='shows'),
        ),
        migrations.AlterField(
            model_name='videolistpluginmodel',
            name='seleccionados',
            field=models.BooleanField(default=False, help_text="Filter by selected videos (Editor's Choice)", verbose_name='selected'),
        ),
        migrations.AlterField(
            model_name='videolistpluginmodel',
            name='series',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('analysis', 'Analysis'), ('revolutionary-women', 'Revolutionary Women'), ('lgbt', 'LGBT'), ('pachamama', 'Pachamama'), ('cultura-latina', 'Cultura Latina')], max_length=58, null=True, verbose_name='series'),
        ),
        migrations.AlterField(
            model_name='videolistpluginmodel',
            name='temas',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('conflicto-en-siria', 'Conflict in Syria'), ('ayotzinapa', 'Ayotzinapa'), ('decide-2014', 'Elections 2014'), ('guerra-economica-en-venezuela', 'Economic War in Venezuela'), ('elecciones-argentina', 'Elections in Argentina'), ('elecciones-chile-2013', '2013 Elections in Chile'), ('contaminacion-ambiental-de-chevron-en-ecuador', "Chevron's Environmental Pollution in Ecuador"), ('conflicto-agrario-colombia', 'Colombia agrarian conflict'), ('catatumbo-resiste', 'Resistance in the Catatumbo'), ('snowden', 'Snowden'), ('asedio-a-la-democracia', 'Harassment to Democracy '), ('elecciones-venezuela-2013', '2013 Elections in Venezuela'), ('hugo-chavez', 'Hugo Chavez'), ('elecciones-ecuador-2013', '2013 Elections in Ecuador '), ('elecciones-eeuu-2012', '2012 Elections in EE.UU.'), ('mercosur', 'Mercosur'), ('crisis-politica-paraguay', 'Political crisis in Paraguay'), ('elecciones-venezuela-2012', '2012 Elections in Venezuela'), ('elecciones-mexico-2012', '2012 Elections in Mexico'), ('energia-nuclear', 'Nuclear energy'), ('violencia-y-narcotrafico', 'Violence and drug trafficking '), ('dictaduras-memoria-y-justicia', 'Dictatorships, history and justice'), ('migracion', 'Migration'), ('cambio-climatico-y-calentamiento-global', 'Climate change and global warming'), ('conflicto-en-medio-oriente', 'Conflict in the Middle East'), ('conflicto-armado-en-colombia', 'Armed conflict in Colombia'), ('revueltas-en-el-mundo-arabe', 'Uprisings in the Middle East'), ('crisis-zona-euro', 'Eurozone economic crisis'), ('derechos-sexuales-y-reproductivos', ' Reproductive rights and sexuality'), ('cine-latinoamericano', 'Latin American film'), ('indigenas-y-pueblos-originarios', 'Native and indigenous peoples '), ('liberaciones-de-las-farc', 'Release of FARC detainees'), ('unasur', 'Unasur'), ('alba', 'ALBA'), ('hambruna-en-africa', 'Famine in Africa '), ('indignados', ' Occupy movement'), ('juegos-olimpicos-londres-2012', 'Olympic Games in London 2012'), ('investigacion-y-avances-cientificos', 'Scientific research and developments '), ('diversidad-sexual', 'Sexual diversity '), ('seguridad-alimentaria', 'Food security'), ('conflicto-por-las-islas-malvinas', 'Malvinas (Falkland) Islands conflict'), ('crisis-del-capitalismo', 'Capitalism in crisis'), ('pederastia-en-la-iglesia-catolica', 'Pedophilia in the Roman Catholic Church '), ('reformas-politicas-y-sociales-en-cuba', 'Political and social reform in Cuba')], max_length=1012, null=True, verbose_name='topics'),
        ),
        migrations.AlterField(
            model_name='videolistpluginmodel',
            name='tiempo',
            field=models.CharField(blank=True, choices=[(None, '- Sin restricci\xf3n -'), ('1h', '1 hora'), ('3h', '3 horas'), ('12h', '12 horas'), ('1d', '1 d\xeda'), ('2d', '2 d\xedas'), ('3d', '3 d\xedas'), ('1s', '1 semana'), ('2s', '2 semanas'), ('1e', '1 mes'), ('2e', '2 meses'), ('1a', '1 a\xf1o'), ('2', '2 a\xf1os')], help_text='Show videos no older that this time', max_length=8, null=True, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='videolistpluginmodel',
            name='tipos',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('noticia', 'News'), ('entrevista', 'Interview'), ('reportaje', 'Report'), ('programa', 'Show'), ('especial-web', 'Snapshot'), ('seriado', 'Web serial'), ('infografia', 'Infographic')], max_length=69, null=True, verbose_name='types'),
        ),
        migrations.AlterField(
            model_name='videolistpluginmodel',
            name='titulo',
            field=models.CharField(blank=True, help_text='Optional title for this listing', max_length=255, verbose_name='title'),
        ),
    ]
