# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('telesurvideos', '0004_auto_20170109_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaListPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='telesurvideos_programalistpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('tipos', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('news', None), ('sports', None), ('analisis', 'An\xe1lisis'), ('cultural', 'Cultural')], max_length=29, null=True, verbose_name='types')),
                ('layout', models.TextField(blank=True, help_text='1, q => full column | 2, w => half column | 3, e => third of column| 4, r => one fourth of column | 6, t => two thirds of column', verbose_name='layout')),
                ('mostrar_mas', models.TextField(blank=True, help_text='1, q => full column | 2, w => half column | 3, e => third of column| 4, r => one fourth of column | 6, t => two thirds of column', verbose_name='show more')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='videolistpluginmodel',
            name='mostrar_descripciones',
            field=models.BooleanField(default=True, verbose_name='display video descriptions'),
        ),
        migrations.AlterField(
            model_name='videolistpluginmodel',
            name='mostrar_titulos',
            field=models.BooleanField(default=True, verbose_name='display video titles'),
        ),
    ]
