# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telesurvideos', '0006_auto_20170110_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolistpluginmodel',
            name='tiempo',
        ),
    ]
