# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-11 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('telesurvideos', '0007_remove_videolistpluginmodel_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programalistpluginmodel',
            name='mostrar_programa',
            field=models.CharField(blank=True, choices=[('logo', 'Mostrar logotipo del programa'), ('banner', 'Mostrar banner del programa'), ('titulo', 'Mostrar t\xedtulo del programa ')], default='logo', max_length=8, null=True, verbose_name='mostrar programa'),
        ),
        migrations.AlterField(
            model_name='programalistpluginmodel',
            name='tipos',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('news', None), ('sports', None), ('analisis', 'An\xe1lisis'), ('cultural', 'Cultural')], help_text='Filtrar \xfanicamente los tipos de programa seleccionado', max_length=29, null=True, verbose_name='types'),
        ),
    ]
